#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#ifdef NODEBUG
#define okay(msg, ...) \
    do                 \
    {                  \
    } while (0)
#define warn(msg, ...) \
    do                 \
    {                  \
    } while (0)
#define fail(msg, ...) \
    do                 \
    {                  \
    } while (0)
#define info(msg, ...) \
    do                 \
    {                  \
    } while (0)
#define printf(msg, ...) \
    do                   \
    {                    \
    } while (0)
#define fprintf(msg, ...) \
    do                    \
    {                     \
    } while (0)
#else
#define okay(msg, ...) printf("[+] " msg "\n", ##__VA_ARGS__)
#define warn(msg, ...) fprintf(stderr, "[!] " msg "\n", ##__VA_ARGS__)
#define fail(msg, ...) fprintf(stderr, "[-] " msg "\n", ##__VA_ARGS__)
#define info(msg, ...) printf("[*] " msg "\n", ##__VA_ARGS__)
#endif

const char *base_words[] = {
    // List of 256 words, you can use your own, make sure they match the builders array. I'd recommend shorter strings for lower entropy.
    "aa",
    "ab",
    "ad",
    "ae",
    "ag",
    "ah",
    "ai",
    "al",
    "am",
    "an",
    "ar",
    "as",
    "at",
    "aw",
    "ax",
    "ay",
    "ba",
    "be",
    "bi",
    "bo",
    "by",
    "da",
    "do",
    "ed",
    "ef",
    "eh",
    "el",
    "em",
    "en",
    "er",
    "es",
    "et",
    "ex",
    "fa",
    "go",
    "ha",
    "he",
    "hi",
    "ho",
    "id",
    "if",
    "in",
    "is",
    "it",
    "jo",
    "ka",
    "ki",
    "la",
    "li",
    "lo",
    "ma",
    "me",
    "mi",
    "mu",
    "my",
    "na",
    "no",
    "nu",
    "od",
    "oe",
    "of",
    "oh",
    "oi",
    "om",
    "on",
    "op",
    "or",
    "os",
    "ow",
    "ox",
    "oy",
    "pa",
    "pe",
    "pi",
    "re",
    "sh",
    "si",
    "so",
    "ta",
    "to",
    "uh",
    "um",
    "un",
    "up",
    "us",
    "ut",
    "we",
    "wo",
    "xi",
    "ye",
    "yo",
    "ace",
    "act",
    "add",
    "ado",
    "age",
    "ago",
    "aid",
    "aim",
    "air",
    "ale",
    "all",
    "amp",
    "and",
    "ant",
    "any",
    "ape",
    "apt",
    "arc",
    "are",
    "ark",
    "arm",
    "art",
    "ash",
    "ask",
    "asp",
    "ate",
    "awe",
    "axe",
    "aye",
    "bad",
    "bag",
    "bah",
    "ban",
    "bar",
    "bat",
    "bay",
    "bed",
    "bee",
    "beg",
    "bet",
    "bid",
    "big",
    "bin",
    "bit",
    "boa",
    "bob",
    "bog",
    "boo",
    "bop",
    "bow",
    "box",
    "boy",
    "bra",
    "bud",
    "bug",
    "bun",
    "bus",
    "but",
    "buy",
    "bye",
    "cab",
    "cad",
    "cam",
    "can",
    "cap",
    "car",
    "cat",
    "caw",
    "cod",
    "cog",
    "con",
    "cop",
    "cow",
    "coy",
    "cry",
    "cub",
    "cue",
    "cup",
    "cur",
    "cut",
    "dab",
    "dad",
    "dam",
    "dan",
    "dap",
    "day",
    "den",
    "dew",
    "did",
    "die",
    "dig",
    "dim",
    "din",
    "dip",
    "doc",
    "doe",
    "dog",
    "don",
    "dot",
    "dry",
    "dub",
    "dud",
    "due",
    "dug",
    "dun",
    "duo",
    "dye",
    "ear",
    "eat",
    "ebb",
    "eel",
    "egg",
    "ego",
    "elf",
    "elm",
    "end",
    "era",
    "ewe",
    "eye",
    "fab",
    "fad",
    "fan",
    "far",
    "fat",
    "fax",
    "fed",
    "fee",
    "fen",
    "few",
    "fib",
    "fig",
    "fin",
    "fit",
    "fix",
    "fly",
    "foe",
    "fog",
    "fox",
    "fry",
    "fun",
    "fur",
    "gab",
    "gad",
    "gag",
    "gal",
    "gap",
    "gas",
    "gay",
    "gel",
    "gem",
    "get",
    "gig",
    "gin",
    "god",
    "got",
    "gum",
    "gun",
    "guy",
    "gym",
    "had",
    "ham",
    "has",
    "hat",
    "hay",
    "hem",
};
const size_t BASE_WORDS_COUNT = 256;
#define MAX_OUTPUT_SIZE 800000
typedef struct
{
    const char *word;
    uint8_t value;
} word_entry_t;

static word_entry_t word_hash_table[512];
static int hash_table_initialized = 0;

// Simple hash
static size_t hash_word(const char *word)
{
    size_t hash = 5381;
    while (*word)
    {
        hash = ((hash << 5) + hash) + *word++;
    }
    return hash % 512;
}

// Initialize hash table
static void init_word_hash_table(const char **shuffled_words, size_t word_count)
{
    if (hash_table_initialized)
        return;

    info("Initializing word lookup hash table...");

    // Clear hash table
    memset(word_hash_table, 0, sizeof(word_hash_table));

    // Insert all words with linear probing for collision resolution
    // This was generated by CLAUDE!! as I was not able to make my previous substitution efficient enough
    for (size_t i = 0; i < word_count; i++)
    {
        if (!shuffled_words[i])
            continue;

        size_t hash = hash_word(shuffled_words[i]);

        // Linear probing to handle collisions
        while (word_hash_table[hash].word != NULL)
        {
            hash = (hash + 1) % 512;
        }

        word_hash_table[hash].word = shuffled_words[i];
        word_hash_table[hash].value = (uint8_t)i;
    }

    hash_table_initialized = 1;
    info("Word lookup hash table initialized with %zu entries", word_count);
}

void shuffle(const char **array, size_t n, unsigned int seed)
{

    unsigned int current_seed = seed;

    // Fisher-Yates shuffle with deterministic random numbers
    for (size_t i = n - 1; i > 0; i--)
    {
        // Simnple LCG for random num
        current_seed = (current_seed * 1103515245 + 12345) & 0x7fffffff;

        // Use the random number to pick an index
        size_t j = current_seed % (i + 1);

        // Swap elements
        const char *temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
}

uint8_t word_to_byte(const char *word, const char **shuffled_words, size_t word_count)
{
    // Initialize hash table on first use
    if (!hash_table_initialized)
    {
        init_word_hash_table(shuffled_words, word_count);
    }

    size_t hash = hash_word(word);

    // Optimized linear probing with limit -> suggested by Claude
    for (int probe = 0; probe < 512; probe++)
    {
        size_t pos = (hash + probe) % 512;

        if (word_hash_table[pos].word == NULL)
        {
            warn("Unknown word: '%s'", word);
            exit(1);
        }

        if (word_hash_table[pos].word[0] == word[0] &&
            strcmp(word_hash_table[pos].word, word) == 0)
        {
            return word_hash_table[pos].value;
        }
    }

    warn("Hash table lookup failed for word: '%s'", word);
    exit(1);
}

void decode(const char *input, const char **shuffled_words, size_t word_count,
            uint8_t *output, size_t *output_len, size_t estimated_output_size)
{

    size_t input_len = strlen(input);
    info("Starting optimized word decoding...");
    info("Input length: %zu characters", input_len);

    // Initialize hash table for fast lookups
    if (!hash_table_initialized)
    {
        init_word_hash_table(shuffled_words, word_count);
    }

    *output_len = 0;
    const char *current = input;
    const char *end = input + input_len;

    char word_buffer[32]; // Buffer for current word
    size_t words_processed = 0;

    while (current < end && *output_len < estimated_output_size - 1)
    {
        // Skip leading spaces
        while (current < end && (*current == ' ' || *current == '\t' || *current == '\n' || *current == '\r'))
        {
            current++;
        }

        if (current >= end)
            break;

        // Find end
        const char *word_start = current;
        while (current < end && *current != ' ' && *current != '\t' && *current != '\n' && *current != '\r')
        {
            current++;
        }

        size_t word_len = current - word_start;
        if (word_len >= sizeof(word_buffer))
        {
            warn("Word too long: %zu characters", word_len);
            exit(1);
        }

        if (word_len == 0)
            continue; // Skip empty words

        memcpy(word_buffer, word_start, word_len);
        word_buffer[word_len] = '\0';

        uint8_t byte_value = word_to_byte(word_buffer, shuffled_words, word_count);
        output[*output_len] = byte_value;
        (*output_len)++;
        words_processed++;
    }

    if (*output_len >= estimated_output_size - 1)
    {
        warn("Output buffer limit reached at %zu bytes (estimated: %zu, words processed: %zu)",
             *output_len, estimated_output_size, words_processed);
        warn("Consider increasing buffer size or checking word encoding");
    }

    info("Word decoding completed: %zu words -> %zu bytes", words_processed, *output_len);
}
size_t count_words(const char *input)
{
    size_t count = 0;
    int in_word = 0;
    const char *ptr = input;

    while (*ptr)
    {
        if (*ptr != ' ' && *ptr != '\t' && *ptr != '\n' && *ptr != '\r' && !in_word)
        {
            in_word = 1;
            count++;
        }
        else if (*ptr == ' ' || *ptr == '\t' || *ptr == '\n' || *ptr == '\r')
        {
            in_word = 0;
        }
        ptr++;
    }

    info("Word count analysis: %zu words found in %zu characters", count, strlen(input));
    return count;
}